version: '3.8'

services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: ldap-server
    hostname: ldap-server
    ports:
      - "389:389"     # LDAP port
      - "636:636"     # LDAPS port
    environment:
      - LDAP_ORGANISATION=Electronic Panopticon
      - LDAP_DOMAIN=electronicpanopticon.com
      - LDAP_BASE_DN=dc=electronicpanopticon,dc=com
      - LDAP_ADMIN_PASSWORD=admin123
      - LDAP_CONFIG_PASSWORD=config123
      - LDAP_READONLY_USER=false
      - LDAP_RFC2307BIS_SCHEMA=false
      - LDAP_BACKEND=mdb
      - LDAP_TLS=true
      - LDAP_TLS_CRT_FILENAME=ldap.crt
      - LDAP_TLS_KEY_FILENAME=ldap.key
      - LDAP_TLS_DH_PARAM_FILENAME=dhparam.pem
      - LDAP_TLS_CA_CRT_FILENAME=ca.crt
      - LDAP_TLS_ENFORCE=false
      - LDAP_TLS_CIPHER_SUITE=SECURE256:-VERS-SSL3.0
      - LDAP_TLS_VERIFY_CLIENT=demand
      - LDAP_REPLICATION=false
      - KEEP_EXISTING_CONFIG=false
      - LDAP_REMOVE_CONFIG_AFTER_SETUP=true
      - LDAP_SSL_HELPER_PREFIX=ldap
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
      - ./ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom
    command: --copy-service
    networks:
      - ldap_network

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: ldap-admin
    hostname: ldap-admin
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - openldap
    networks:
      - ldap_network

volumes:
  ldap_data:
  ldap_config:

networks:
  ldap_network:
    driver: bridge
